END_KEYWORDS = [
    "https://",
    "Fichier",
    "B o o k s ta c k s",
    "B o o k s t a c k s",
    "Month:",
    "MONTH:",
    "USER JOURNAL TITLE",  # ?
    "OCLC #:",
    "URL",
    "Stable URL:",
]
KEYWORDS = [
    "Author(s):",
    "Source:",
    "Published By:",
    "Published by:",
    "PUBLISHED BY:",
    "Volume:",
    "Vol.",
    "VOLUME:",
    "tome",
    "Issue:",
    "ISSUE:",
    "Month/Year:",
    "Year:",
    "YEAR:",
    "Year Published:",
    "Pages:",
    "pp.",
    "PAGES:",
    "Artide Author:",
    "ARTICLE AUTHOR:",
    "ARTICLE TITLE:",
    "Artide Title:",
    "Article Author:",
    "Article Title:",
    "ISBN:",
    "ISSN:",
    "TYPE:",
    "Type:",
    "Journal Name:",
    "Journal Title:",
    "JOURNAL TITLE:",
    "Journal:",
    "In:",
    "doi:",
    "DOI:",
]
